### ISSUE TITLE
Project Planning

### ISSUE THREAD

**Issue by Jyustin** [vardaansinha/stg#1]
topic for project: news and information

news and information fulfills criteria

includes frontend/backend for information and output of information
maybe input can be used

**Comment by STG-7** [comment]
Plan for Shaurya Goel: Sports news with NBA and NFL statistics. Using a table which represents scores, upcoming stats, and game predictions.

**Comment by NavanYatavelli** [comment]
Breaking news - police chase/ suspect found

Use of images + markdown + text styling

**Comment by vardaansinha** [comment]
Weather API

A separate tab which will incorporate a weather API for areas across the world.

**Comment by Jyustin** [comment]
daily inspirational quote/ funny

a new tab that would give you a neat daily inspirational quote or something funny. would pull from  list. could display something new every 24 hours
